### ISSUE TITLE
First start

### ISSUE THREAD

**Issue by hotlittlewhitedog** [SchweGELBin/OpenBible2#15]
👍  Congratulations & Keep Courage with your new Bible (baby) app.   
Time is short and the apocalypse is at the door.  
If I can give you an advice; focus on important things: to have something useable & make it simple.   

If you need some inspirations for the design, you can check my 3 Bibles apps (I'm on gitlab or via my website).  

I don't have time for dev to help you (I'm already on mine), but I will check your updates and might create issues.  
We are all in the boat of Jesus :)   
 
Your app could be useful for languages not managed in other Bible apps as you use Sword.  

0) Something goes wrong during the first adaptation of settings and playing with Chapter... Maybe you have to disable the widgets.  
1) Maybe you have to add a progress (circular) when it works in background.  
2) Home Screen is maybe not necessary actually and could be implemented in another way.  
3) You should not close the app when exiting the settings 
 
++

**Comment by SchweGELBin** [comment]
Hey, thank you very much! I'll try to follow your suggestions.
If I remember correctly, you are the dev of "The Light", which I found on F-Droid.
If you are interested in the Sword translations, I can recommend you to check out [AndBible](https://github.com/AndBible/and-bible).

Have a great day! 😁

**Comment by hotlittlewhitedog** [comment]
"you are the dev of "The Light" >> Indeed with "The Life"... 😸 
I installed AndBible, a good app, I suggested it to people in the need of some translations I can't provide 👍  
Perso I prefer open source apps than YouVersion...

**Comment by SchweGELBin** [comment]
Hey, I implemented all of your suggestions by adding a "Getting Started" at first time launch.
Basically it makes sure to download all the necessary files and tells the user to wait.
It also lets the user choose their default translation.
I also removed the Home Screen and added a Selection Screen that opens when clicking on the title in the Read Screen.

It will be available in `v1.0.0`

I'm closing the issue as I see it as resolved. Feel free to reopen it or create a new one.
Have a great day!
