### ISSUE TITLE
As a new bible reader, which translation should I choose?

### ISSUE THREAD

**Issue by femdiya** [SchweGELBin/OpenBible2#18]
The title is self explanatory. I wanted to read the bible for the very first time (first time because I live in a Muslim country).
Which translation should I choose?

**Comment by SchweGELBin** [comment]
Hello, I can only speak for german, as I only read the Bible in german.
I like `Schlachter` the most, followed by `Luther` and `Elberfelder`, but that's just preference.
But from your message I don't think you undestand german, I'd suggest reading in your native language to understand things better and to not misinterpret things.

Some translation are older/newer and some take the focus on accuracy, whilst other focus on being easy to understand.
I'd suggest starting with an "easy" translation, but as I wrote, I can't compare things, which I don't have experience with.

I'm sorry, maybe someone else can help.

Anyways, have a great day!

**Comment by femdiya** [comment]
Hey and thanks for the response.
No, I don't understand German, my main language is Persian and I didn't find any translation for Persian there?

**Comment by SchweGELBin** [comment]
Hey, you are right. I'm sorry for you, but I can't just add a persian translation as the scripture is provided by a third party (getBible).
So you either need to read in another language like english or find another app that has a persian translrtion.
I'd recommend using another app if you can find one.

Here is a full list if all the supported translations:

```
Afrikaans, Arabic, Armenian, Basque
Breton
Chamorro, Cherokee, Chinese, Coptic, Croatian, Czech
Danish, Dutch
English, Esperanto, Estonian
Finnish, French
German, Gothic, Greek Modern, Greek
Hebrew, Hungarian
Italian
Japanese
Korean
Latin, Latvian, Lithuanian
Manx Gaelic,Maori, Myanmar Burmse
Norwegian bokmal
Portuguese, Potawatomi
Romanian, Russian
Scottish Gaelic, Slavonic Elizabeth, Spanish,Swahili, Swedish, Syriac
Tagalog, Thai, Turkish
Ukrainian, Uma
Vietnamese
```

**Comment by SchweGELBin** [comment]
After researching a bit, I found [Quick Bible](https://github.com/yukuku/androidbible), which also has a persion translation (Farsi).
I hope this helps. Otherwise, you can read in english or both.

I'm closing this issue for now. If you have any questions, just reopen it.
(I just don't want too many open issues)

Have a great day!

**Comment by femdiya** [comment]
Thank you so much for the comment, there's a small issue tho..
I will ofc try that app and try to read in Persian language, but my point is what's the best translation for new cormers to bible readers which is a professional translation and quite easy to understand.
Thanks again so much for the response.
