### ISSUE TITLE
[Feature Request] Split screen for translations

### ISSUE THREAD

**Issue by Donkey-Doug** [SchweGELBin/OpenBible2#5]
Quick bible has support for split screen of two different translations. Example:

![Screenshot_20241112-222242_Trebuchet](https://github.com/user-attachments/assets/a90a5126-01a7-44e3-bb05-8d034d0878c2)

I would love to have this feature in openbible.

**Comment by SchweGELBin** [comment]
Hey, thank you for the suggestion.
I added it to `v1.2.0`, but the split is vertical not horizontal.
I hope, this is okay.

Have a great day!
