### ISSUE TITLE
[Feature Request] Reduce padding on the sides

### ISSUE THREAD

**Issue by Donkey-Doug** [SchweGELBin/OpenBible2#7]
Currently a large part on the left and right of the screen is padding:

![Screenshot_20241112-222616_Trebuchet](https://github.com/user-attachments/assets/3e262acb-8ffe-4ae3-a880-747fdb078254)

I suggest to reduce the padding.

**Comment by SchweGELBin** [comment]
Thank you for the suggestion!
Here you go: *(Part of)* 4d3bebe99782f0431b37ad625db0d72ab2647940

Available in `v0.5.0+`.
